#Psuedo code
# Enter player 1's choice
# Enter player 2's choice
# define if 1 = this and 2 = this then player this wins.
# add *** NO CHEATING *** multiple lines after a user enters input.
print("Welcome to the Rock Paper Scissors Lame Version CLI :D")
player_1 = input("Player 1 Enter your name: ")
player_2 = input("Player 2 Enter your name: ")
choice_1 = input(f"Hii {player_1}, Enter your choice: ")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
print("*** !!! NO CHEATING !!! ***")
choice_2 = input(f"Hii {player_2}, Enter your choice: ")

if (choice_1 == "rock") and (choice_2 == "paper"):
    print(f'\n{player_2} WINS!!')

elif (choice_1 == "rock") and (choice_2 == "scissors"):
    print(f'\n{player_1} WINS!!')

elif (choice_1 == "paper") and (choice_2 == "rock"):
    print(f'\n{player_1} WINS!!')

elif (choice_1 == "paper") and (choice_2 == "scissors"):
    print(f'\n{player_2} WINS!!')

elif (choice_1 == "scissors") and (choice_2 == "rock"):
    print(f'\n{player_2} WINS!!')

elif (choice_1 == "scissors") and (choice_2 == "paper"):
    print(f'\n{player_1} WINS!!')

elif (choice_1 == "rock") and (choice_2 == "rock"):
    print("\nIt's a draw!!")

elif (choice_1 == "paper") and (choice_2 == "paper"):
    print("\nIt's a draw!!")

elif (choice_1 == "scissors") and (choice_2 == "scissors"):
    print("\nIt's a draw!!")
else:
    print("U wot m8..!!")